apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-daemonset
spec:
  mode: daemonset
  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otelcol'
            scrape_interval: 10s
            static_configs:
            - targets: ['0.0.0.0:8888']
            metric_relabel_configs:
              - source_labels: [ __name__ ]
                regex: '.*grpc_io.*'
                action: drop
      jaeger:
        protocols:
          grpc:
      otlp:
        protocols:
          grpc:
          http:
    processors:

    exporters:
      logging:
        loglevel: debug
      otlp:
        endpoint: http://tempo-tempo-distributed-query-frontend.tempo:3100

    service:
      pipelines:
        traces:
          receivers: [prometheus, otlp, jaeger]
          processors: []
          exporters: [logging, otlp]
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [logging]
