apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-daemonset
spec:
  mode: daemonset
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
      otlp:
        protocols:
          grpc:
          http:
      
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otelcol'
              scrape_interval: 10s
              static_configs:
              - targets: ['0.0.0.0:8888']
              metric_relabel_configs:
                - source_labels: [ __name__ ]
                  regex: '.*grpc_io.*'
                  action: drop
    processors:

    exporters:
      logging:
        loglevel: debug
      otlp:
        endpoint: mk.tempo.192.168.64.25.nip.io:443
        tls:
          insecure_skip_verify: true

    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: []
          exporters: [logging, otlp]
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [logging]
