# -- Install and upgrade CRDs
installCRDs: true
# -- Keep CRD's on helm uninstall
keepCRDs: false

controller:
  image:
    tag: v1.2.0-rc2 # comment out if pre-release or other than the chart defined versions not required. Version override to use rc version which is not possible with argo helm chart as it only supports stable version
dashboard:
  # -- Deploy dashboard server
  enabled: true
  ingress:
    enabled: true
    annotations: {}
    labels: {}
    ingressClassName: "nginx"

    hosts:
      - mk.rollouts.local

    paths:
      - /
    pathType: Prefix
    extraPaths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation

    # -- Dashboard ingress tls
    tls:
    # - secretName: argorollouts-example-tls
      - hosts:
          - mk.rollouts.local

metrics:
    # -- Deploy metrics service
    enabled: true
    serviceMonitor:
      # -- Enable a prometheus ServiceMonitor
      enabled: true
      # -- Labels to be added to the ServiceMonitor
      additionalLabels: 
        release: prometheus-operator
      # -- Annotations to be added to the ServiceMonitor
      additionalAnnotations: {}