apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
spec:
  generators:
    - clusters: {} # all clusters managed by argocd
  template:
    metadata:
      name: '{{name}}-ingres-nginx'
    spec:
      project: cluster-addons
      source:
        repoURL: 'https://github.com/logamanig/sample-argocd-apps'
        targetRevision: master
        path: env/devops/cluster-addons/ingress-nginx

      destination:
        server: '{{server}}'
        namespace: ingress-nginx

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2