# Manage ONLY GRAFANA resources as part of this kustomize deployment
# and disable all other resources related to Prometheus and metrics
# as those other resources to be deployed in all clusters as part of cluster addon argocd applicationset
kind: Kustomization

resources:
  - "./resources/ds-devops-cluster.yaml"
  
helmCharts:
  - repo: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 35.5.1
    includeCRDs: true
    namespace: monitoring
    releaseName: grafana
    valuesFile: values.yaml

patchesStrategicMerge:
  # to force argocd to replace(create/recreate) instead appling this crd as a workaround for it's name too long issue
  - "./overlays/crd-prometheuses.monitoring.coreos.com.yaml"