apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: shared
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:18.0.0
          args: ["start-dev"]
          env:
            # refer https://www.keycloak.org/server/all-config for keycloak environment variable
            # - name: KC_HOSTNAME
            #   value: mk.sso.local
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_LOG_LEVEL
              value: info
            - name: KC_PROXY
              value: edge
            # - name: KC_DB
            #   value: postgres
            # - name: KC_DB_URL_HOST
            #   value: <DB_SERVER_HOST>
            # - name: KC_DB_URL_DATABASE
            #   value: keycloak
            # - name: KC_DB_URL
            #   value: jdbc:postgresql://${KC_DB_URL_HOST}/${KC_DB_URL_DATABASE}?currentSchema=${KC_DB_SCHEMA}
            # - name: KC_DB_SCHEMA
            #   value: keycloak
            # - name: KC_DB_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: keycloak-secret
            #       key: username
            # - name: KC_DB_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: keycloak-secret
            #       key: password
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
