# Diable all except grafana as other resources to managed by prometheus cluster addon
# Manage ONLY GRAFANA resources as part of this kustomize deployment
# and disable all other resources related to Prometheus and metrics
# as those other resources to be deployed in all clusters as part of cluster addon argocd applicationset
defaultRules:
  create: false

alertmanager:
  enabled: true

  ingress:
    enabled: true

    ingressClassName: nginx

    annotations: {}

    labels: {}

    hosts:
      - mk.alertmanager.local

    paths:
      - /

    pathType: ImplementationSpecific

    tls:
      - hosts:
          - mk.alertmanager.local
    # - secretName: alertmanager-general-tls
    #   hosts:
    #   - mk.alertmanager.local

nodeExporter:
  enabled: false

grafana:
  enabled: true

  ingress:
    enabled: true

    ingressClassName: nginx
    annotations: {}
    labels: {}

    hosts:
      - mk.grafana.local

    path: /

    tls:
      - hosts:
          - mk.grafana.local
    # - secretName: grafana-tls
    #   hosts:
    #   - mk.grafana.local

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"

      ## Annotations for Grafana dashboard configmaps
      ##
      annotations: {}
      multicluster:
        global:
          enabled: true
        etcd:
          enabled: false
      provider:
        allowUiUpdates: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true

      ## URL of prometheus datasource
      ##
      # url: http://prometheus-stack-prometheus:9090/

      # If not defined, will use prometheus.prometheusSpec.scrapeInterval or its default
      # defaultDatasourceScrapeInterval: 15s

      ## Annotations for Grafana datasource configmaps
      ##
      annotations: {}

      ## Create datasource for each Pod of Prometheus StatefulSet;
      ## this uses headless service `prometheus-operated` which is
      ## created by Prometheus Operator
      ## ref: https://git.io/fjaBS
      createPrometheusReplicasDatasources: false
      label: grafana_datasource
      labelValue: "1"

    additionalDataSources:
      - name: loki
        type: loki
        url: http://loki-loki-distributed-gateway.loki

      - name: tempo
        type: tempo
        url: http://tempo-tempo-distributed-query-frontend.tempo:3100

kubeApiServer:
  enabled: false

kubelet:
  enabled: false

kubeControllerManager:
  enabled: false

coreDns:
  enabled: false

kubeDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

kubeStateMetrics:
  enabled: false

prometheusOperator:
  enabled: false

prometheus:
  enabled: true
