# Diable all except grafana as other resources to managed by prometheus cluster addon
# Manage ONLY GRAFANA resources as part of this kustomize deployment
# and disable all other resources related to Prometheus and metrics
# as those other resources to be deployed in all clusters as part of cluster addon argocd applicationset
defaultRules:
  create: false

alertmanager:
  enabled: false

grafana:
  enabled: true

  ingress:
    enabled: true

    annotations: {}
    labels: {}

    # hosts:
    #   - mk.grafana.local
    
    path: /

    tls: []
    # - secretName: grafana-general-tls
    #   hosts:
    #   - grafana.example.com

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"

      ## Annotations for Grafana dashboard configmaps
      ##
      annotations: {}
      multicluster:
        global:
          enabled: true
        etcd:
          enabled: false
      provider:
        allowUiUpdates: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true

      ## URL of prometheus datasource
      ##
      # url: http://prometheus-stack-prometheus:9090/

      # If not defined, will use prometheus.prometheusSpec.scrapeInterval or its default
      # defaultDatasourceScrapeInterval: 15s

      ## Annotations for Grafana datasource configmaps
      ##
      annotations: {}

      ## Create datasource for each Pod of Prometheus StatefulSet;
      ## this uses headless service `prometheus-operated` which is
      ## created by Prometheus Operator
      ## ref: https://git.io/fjaBS
      createPrometheusReplicasDatasources: false
      label: grafana_datasource
      labelValue: "1"

kubeApiServer:
  enabled: false

kubelet:
  enabled: false

kubeControllerManager:
  enabled: false

coreDns:
  enabled: false

kubeDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

kubeStateMetrics:
  enabled: false

prometheusOperator:
  enabled: false

prometheus:
  enabled: false

prometheus-operator:
  enabled: false
