# kind: Kustomization
# namespace: argocd

# resources:
#   - "./resources/argocd-install.yaml"
#   - "./resources/ingress.yaml"

# patches:
#   - target:
#       kind: ConfigMap
#       name: argocd-cm
#     path: ./overlays/argocd-cm.yaml

kind: Kustomization

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 4.0.1
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml
    includeCRDs: true

# patchesStrategicMerge:
#   - ./overlays/argocd-cm.yaml