kind: Kustomization

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 4.0.1
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml
    includeCRDs: true
