server:
  config:
    url: mk.argocd.local

    # To enable helm install through kustomize in argocd
    kustomize.buildOptions: --enable-helm

    resource.customizations.ignoreDifferences: |
      #fixes out of sync issue for kynervo and handles the autogen rule exclusion without ignoring the base rule definitions
      - group: kyverno.io
        kind: ClusterPolicy
        jqPathExpressions:
          - .spec.rules[] | select(.name|test("autogen-."))

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    ingressClassName: nginx
    hosts:
      - mk.argocd.local
    tls:
      - hosts:
          - mk.argocd.local
