global:
  enabled: true
  tlsDisabled: true
  psp:
    enabled: false

injector:
  enabled: false

server:
  enabled: true
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    ingressClassName: nginx
    hosts:
      - host: mk.vault.local
    tls:
      - hosts:
        - mk.vault.local
        
ui:
  enabled: true