kind: Kustomization

resources:
  - "./resources/leader-election-role.yaml"
  
patchesStrategicMerge:
  - "./overlays/jaeger-crd.yaml"

helmCharts:
  - repo: https://jaegertracing.github.io/helm-charts
    name: jaeger-operator
    version: 2.32.1
    includeCRDs: true
    namespace: monitoring
    releaseName: jaeger-operator
    valuesFile: values.yaml