image:
  tag: 1.33.0

jaeger:
  create: true
  spec:
    # strategy: production
    allInOne:
      image: jaegertracing/all-in-one:1.33.0

    storage:
      type: badger

    options:
      prometheus: http://prometheus-operator-kube-p-prometheus:9090
    metricStorage:
      type: prometheus

    ingress:
      enabled: true
      hosts:
        - mk.jaeger.local