# image:
#   tag: 1.31.0

jaeger:
  create: true
  spec:
    strategy: allInOne # production
    allInOne:
      image: jaegertracing/all-in-one:1.33.0
      options:
        prometheus:
          server-url: http://prometheus-operator-kube-p-prometheus:9090
      metricsStorage:
        type: prometheus

    storage:
      options:
        memory:
          max-traces: 100000

    ingress:
      enabled: true
      hosts:
        - mk.jaeger.local