image:
  tag: 1.32.0

jaeger:
  create: true
  spec:
    # strategy: production
    allInOne:
      image: jaegertracing/all-in-one:1.33.0

      options:
        prometheus: http://prometheus-operator-kube-p-prometheus:9090
      metricsStorage:
        type: prometheus

    storage:
      type: badger

    ingress:
      enabled: true
      hosts:
        - mk.jaeger.local