image:
  tag: 1.34.1

jaeger:
  create: true
  spec:
    # strategy: production
    allInOne:
      image: jaegertracing/all-in-one:1.35.1
      options:
        prometheus:
          server-url: http://prometheus-operator-kube-p-prometheus:9090
      metricsStorage:
        type: prometheus

    storage:
      type: badger

    ingress:
      enabled: true
      hosts:
        - mk.jaeger.local