kind: Kustomization

helmCharts:
  - repo: https://kedacore.github.io/charts
    name: keda
    version: 2.7.0
    includeCRDs: true
    namespace: system-addons
    releaseName: keda
    valuesFile: values.yaml