kind: Kustomization

resources:
  - "./resources/use-certmanager-cert-as-linkerd-issuer-cert.yaml"
  - "./resources/linkerd-viz-ingress.yaml"

helmCharts:
  - repo: https://helm.linkerd.io/stable
    name: linkerd2
    version: 2.11.1
    releaseName: linkerd
    namespace: linkerd
    valuesFile: linkerd-values.yaml

  - repo: https://helm.linkerd.io/stable
    name: linkerd2-cni
    version: 2.11.1
    releaseName: linkerd-cni
    namespace: linkerd-cni
    valuesFile: linkerd-cni-values.yaml

  - repo: https://helm.linkerd.io/stable
    name: linkerd-viz
    version: 2.11.1
    releaseName: linkerd-viz
    namespace: linkerd-viz
    valuesFile: linkerd-viz-values.yaml
  
  - repo: https://flagger.app
    name: flagger
    version: 1.19.0
    releaseName: flagger
    namespace: linkerd
    includeCRDs: true
    valuesFile: flagger-values.yaml