prometheusUrl: http://prometheus-operator-kube-p-prometheus.monitoring.svc.cluster.local:9090
jaegerUrl: http://jaeger-operator-jaeger-query.monitoring.svc.cluster.local:16686

prometheus:
  enabled: false

grafana:
  externalUrl: https://mk.grafana.local
  uidPrefix: linkerd-dashboard