kind: Kustomization

resources:
  - "./resources/opentelemetry-collector.yaml"
  - "./resources/servicemonitor-otelcol-metrics.yaml"

helmCharts:
  - repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    name: opentelemetry-operator
    version: 0.7.0
    includeCRDs: true
    namespace: monitoring
    releaseName: opentelemetry-operator
    valuesFile: values.yaml