apiVersion: v1
data:
  datasource.yaml: |-
    datasources:
    - name: Loki
      type: loki
      url: http://loki-loki-distributed-gateway.loki
      access: proxy
      isDefault: false
      editable: false
      version: 1
      jsonData:
        timeInterval: 30s
kind: ConfigMap
metadata:
  name: grafana-kube-prometheus-st-grafana-datasource
