apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devops-tools-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/logamanig/sample-argocd-apps
        revision: master
        directories:
          - path: env/devops/tools/*

          - path: env/devops/tools/vault
            exclude: true # vault excluded as it's not required in test env 

  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: cluster-addons
      source:
        repoURL: https://github.com/logamanig/sample-argocd-apps
        targetRevision: master
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}' # Comment out to use namespace specified in the deployed resource yaml/helm/kustomize
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true