kind: Kustomization

resources:
  - "./resources/podmonitor.yaml"

helmCharts:
  - repo: https://dapr.github.io/helm-charts/
    name: dapr
    version: 1.7.4
    releaseName: dapr
    valuesFile: values.yaml
    includeCRDs: true
    namespace: system-addons