kind: Kustomization

helmCharts:
  - repo: https://grafana.github.io/helm-charts
    name: loki-distributed
    version: 0.45.1
    namespace: monitoring
    includeCRDs: true
    releaseName: loki
    valuesFile: values.yaml
    