apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name: dapr-pod-monitor
  labels:
    name: dapr-pod-monitor
    release: prometheus-operator

spec:
  namespaceSelector:
    matchNamespace:
      - tools
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: dapr