apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dapr-podmonitor
  labels:
    name: dapr-podmonitor
    release: prometheus-operator
spec:
  namespaceSelector:
    matchNames:
      - "tools"
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: dapr