kind: Kustomization

helmCharts:
  - repo: https://grafana.github.io/helm-charts
    name: tempo-distributed
    version: 0.18.0
    namespace: monitoring
    includeCRDs: true
    releaseName: tempo
    valuesFile: values.yaml
    