apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-ds-grafana
  labels:
    grafana_datasource: "1"
    namespace: prometheus-operator
data:
  jaeger-ds.yaml: |-
    apiVersion: 1
    datasources:
      - name: Jaeger
        uid: jaeger
        type: jaeger
        url: http://jaeger-operator-jaeger-query.jaeger-operator:16686
        access: proxy
        isDefault: false
        editable: false
        jsonData:
          timeInterval: 30s
          nodeGraph:
            enabled: true
          tracesToLogs:
            datasourceUid: loki
            tags: ['job', 'instance', 'pod', 'namespace']
            mappedTags: [{ key: 'service.name', value: 'service' }]
            mapTagNamesEnabled: false
            spanStartTimeShift: '1h'
            spanEndTimeShift: '1h'
            filterByTraceID: true
            filterBySpanID: true
            lokiSearch: true
          search:
            hide: false
