apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki-loki-distributed-gateway.loki
      access: proxy
      isDefault: false
      editable: false
      version: 1
      jsonData:
        timeInterval: 30s
kind: ConfigMap
metadata:
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/instance: prometheus-operator
    grafana_datasource: '2'
    release: grafana
  name: grafana-kube-prometheus-st-loki-datasource
  namespace: prometheus-operator
