kind: Kustomization

helmCharts:

  - repo: https://kyverno.github.io/kyverno/
    name: kyverno
    version: v2.3.3 
    namespace: system-addons
    releaseName: kyverno
    valuesFile: kyverno-values.yaml
    
  - repo: https://kyverno.github.io/kyverno/
    name: kyverno-policies
    version: v2.3.3
    namespace: system-addons
    releaseName: kyverno-policies
    valuesFile: kyverno-policies-values.yaml