# image:
#   repository: k8s.gcr.io/external-dns/external-dns
#   # Overrides the image tag whose default is v{{ .Chart.AppVersion }}
#   tag: ""
#   pullPolicy: IfNotPresent

# deploymentAnnotations: {}
# podAnnotations: {}

serviceMonitor:
  enabled: true
  additionalLabels:
    # required for prometheus-operator
    release: prometheus-operator
  interval: 1m
  scrapeTimeout: 10s

provider: azure