kind: Kustomization

helmCharts:
  - repo: https://dapr.github.io/helm-charts/
    name: dapr
    version: 1.7.0
    releaseName: dapr
    valuesFile: values.yaml
    includeCRDs: true
    namespace: tools