apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons-linkerd-stack-appset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/logamanig/sample-argocd-apps
              revision: master
              directories:
                - path: env/cluster-addons/linkerd-stack/*

          - clusters: {} # all registered clusters in argocd
              # selector:
              #   matchLabels:
              #     argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
      namespace: argocd
      labels:
        appset: cluster-addons-linkerd-stack-appset
    spec:
      project: cluster-addons
      source:
        repoURL: https://github.com/logamanig/sample-argocd-apps
        targetRevision: master
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true