apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons-system-addons-appset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/logamanig/sample-argocd-apps
              revision: master
              directories:
                - path: env/cluster-addons/system-addons/*

                - path: env/cluster-addons/system-addons/external-secrets
                  exclude: true
                - path: env/cluster-addons/system-addons/ingress-nginx
                  exclude: true # ingress excluded as this sample running on minukube with ingress addon enabled
                - path: env/cluster-addons/system-addons/external-dns
                  exclude: true # not required in minikube environment
                - path: env/cluster-addons/system-addons/argo-rollouts
                  exclude: true # Exlcuded in favour of flagger (add through linkerd argocd app)
                  
          - clusters: {} # all registered clusters in argocd
              # selector:
              #   matchLabels:
              #     argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
      namespace: argocd
      labels:
        appset: cluster-addons-system-addons-appset
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: cluster-addons
      source:
        repoURL: https://github.com/logamanig/sample-argocd-apps
        targetRevision: master
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: system-addons
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true # for kynervo policies