# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: cluster-addons-dedicated-ns-appset
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   generators:
#     - matrix:
#         generators:
#           - git:
#               repoURL: https://github.com/logamanig/sample-argocd-apps.git
#               revision: master
#               directories:
#                 - path: env/cluster-addons/dedicated-ns/*
                  
#           - clusters: {} # all registered clusters in argocd
#               # selector:
#               #   matchLabels:
#               #     argocd.argoproj.io/secret-type: cluster
#   template:
#     metadata:
#       name: '{{path.basename}}-{{name}}'
#       namespace: argocd
#       labels:
#         appset: cluster-addons-dedicated-ns-appset
#       finalizers:
#         - resources-finalizer.argocd.argoproj.io
#     spec:
#       project: cluster-addons
#       source:
#         repoURL: https://github.com/logamanig/sample-argocd-apps.git
#         targetRevision: master
#         path: '{{path}}'
#       destination:
#         server: '{{server}}'
#         namespace: '{{path.basename}}'
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true
#         syncOptions:
#           - CreateNamespace=true