apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: linkerd
    server: 'https://kubernetes.default.svc'
  source:
    path: env/cluster-addons/linkerd
    repoURL: 'https://github.com/logamanig/sample-argocd-apps'
    targetRevision: master
  project: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
