kind: Kustomization

resources:
  - "./resources/linkerd-viz-ingress.yaml"

helmCharts:
  - repo: https://helm.linkerd.io/stable
    name: linkerd-viz
    version: 2.11.1
    releaseName: linkerd-viz
    namespace: linkerd-viz
    valuesFile: linkerd-viz-values.yaml
  
  - repo: https://helm.linkerd.io/stable
    name: linkerd-jaeger
    version: 2.11.1
    releaseName: linkerd-jaeger
    namespace: linkerd-jaeger
    valuesFile: linkerd-jaeger-values.yaml