alertmanager:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: true

  service:
    port: 80
  
  ingress:
    enabled: true
    hosts:
      - mk.prometheus.local
    paths:
      - /
    tls:
      - hosts:
          - mk.prometheus.local