alertmanager:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: true

  service:
    port: 9090

    additionalPorts:
      - http: 80
      - https: 443
  
  ingress:
    enabled: true
    hosts:
      - mk.prometheus.local
    paths:
      - /
    # tls:
    #   - hosts:
    #       - mk.prometheus.local

prometheus-operator:
  tls:
    enabled: true
  admissionWebhooks: 
    enabled: true
    patch:
      podAnnotations:
        linkerd.io/inject: disabled
  # Use certmanager to generate webhook certs
    certManager:
      enabled: true
      # self-signed root certificate
      rootCert:
        duration: ""  # default to be 5y
      admissionCert:
        duration: ""  # default to be 1y
      # issuerRef:
      #   name: "issuer"
      #   kind: "ClusterIssuer"
