alertmanager:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: true

  service:
    port: 80
  
  ingress:
    enabled: true
    hosts:
      - mk.prometheus.local
    paths:
      - /
    # tls:
    #   - hosts:
    #       - mk.prometheus.local

prometheus-operator:
  tls:
    enabled: false
  admissionWebhooks: 
    enabled: false
  # Use certmanager to generate webhook certs
    certManager:
      enabled: false
      # self-signed root certificate
      rootCert:
        duration: ""  # default to be 5y
      admissionCert:
        duration: ""  # default to be 1y
      # issuerRef:
      #   name: "issuer"
      #   kind: "ClusterIssuer"
