kind: Kustomization

resources:
  - "./resources/use-certmanager-cert-as-linkerd-issuer-cert.yaml"

helmCharts:
  - repo: https://helm.linkerd.io/stable
    name: linkerd2
    version: 2.11.1
    releaseName: linkerd
    namespace: linkerd
    valuesFile: linkerd-values.yaml

  - repo: https://helm.linkerd.io/stable
    name: linkerd-viz
    version: 2.11.1
    releaseName: linkerd-viz
    namespace: linkerd 
    valuesFile: linkerd-viz-values.yaml