kind: Kustomization
namespace: linkerd

resources:
  - "./resources/use-certmanager-cert-as-linkerd-issuer-cert.yaml"

helmCharts:
  - repo: https://helm.linkerd.io/stable
    name: linkerd2
    version: 2.11.1
    releaseName: linkerd
    valuesFile: values.yaml

  - repo: https://helm.linkerd.io/stable
    name: linkerd-viz
    version: 2.11.1
    releaseName: linkerd
    valuesFile: values.yaml