kind: Kustomization
namespace: cert-manager

resources:
  - "./resources/linkerd-cert-issuer.yaml"

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.7.1
    releaseName: cert-manager
    valuesFile: values.yaml
    includeCRDs: true

  - name: cert-manager-trust
    repo: https://charts.jetstack.io
    version: 0.1.1
    releaseName: cert-manager-trust
    includeCRDs: true