kind: Kustomization
namespace: cert-manager

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.7.1
    releaseName: cert-manager
    valuesFile: values.yaml
    includeCRDs: true