kind: Kustomization

helmCharts:
  - repo: https://flagger.app
    name: flagger
    version: 1.19.0
    releaseName: flagger
    namespace: linkerd
    includeCRDs: true
    valuesFile: flagger-values.yaml