kind: Kustomization

resources:
  - "./resources/use-certmanager-cert-as-linkerd-issuer-cert.yaml"

helmCharts:
  - repo: https://helm.linkerd.io/edge
    name: linkerd-crds
    version: 1.1.0-edge
    releaseName: linkerd-crds
    namespace: linkerd
    valuesFile: values.yaml

  - repo: https://helm.linkerd.io/edge
    name: linkerd-crds
    version: 1.2.0-edge
    releaseName: linkerd-control-plane
    namespace: linkerd
    valuesFile: values.yaml