kind: Kustomization

resources:
  - "./resources/use-certmanager-cert-as-linkerd-issuer-cert.yaml"

helmCharts:
  - repo: https://helm.linkerd.io/edge
    name: linkerd2-cni
    version: 30.0.12-edge
    releaseName: linkerd-cni
    namespace: linkerd
    valuesFile: linkerd-cni.yaml

  - repo: https://helm.linkerd.io/edge
    name: linkerd-crds
    version: 1.1.0-edge
    includeCRDs: true
    releaseName: linkerd-crds
    namespace: linkerd

  - repo: https://helm.linkerd.io/edge
    name: linkerd2
    version: 2.11.1
    releaseName: linkerd-control-plane
    namespace: linkerd
    includeCRDs: true
    valuesFile: linkerd-values.yaml