kind: Kustomization

resources:
  - "./resources/use-certmanager-cert-as-linkerd-issuer-cert.yaml"

helmCharts:
  # - repo: https://helm.linkerd.io/stable
  #   name: linkerd-crds
  #   version: 1.11.1
  #   includeCRDs: true
  #   releaseName: linkerd-crds
  #   namespace: linkerd

  - repo: https://helm.linkerd.io/stable
    name: linkerd2
    version: 1.11.1
    releaseName: linkerd
    namespace: linkerd
    includeCRDs: true
    valuesFile: values.yaml