apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- ./overlays/ingress.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.3/manifests/install.yaml