apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devops-shared-appset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: https://github.com/logamanig/sample-argocd-apps
        revision: master
        directories:
          - path: env/devops/shared/*

  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
      labels:
        appset: devops-shared-appset
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: devops
      source:
        repoURL: https://github.com/logamanig/sample-argocd-apps
        targetRevision: master
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: shared
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true