apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devops-system-addons-appset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: https://github.com/logamanig/sample-argocd-apps.git
        revision: master
        directories:
          - path: env/devops/system-addons/*

          - path: env/devops/system-addons/vault
            exclude: true # vault excluded as it's not required in test env 

  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
      labels:
        appset: devops-system-addons-appset
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: devops
      source:
        repoURL: https://github.com/logamanig/sample-argocd-apps.git
        targetRevision: master
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: system-addons
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true