kind: Kustomization
# namespace: system-addons # Namespace must be not mentioned at the kustomize level to let webhook service to be provisioned to the default namespace as it required

resources:
  - "./resources/linkerd-cert-issuer.yaml"

helmCharts:
  - repo: https://charts.jetstack.io
    name: cert-manager
    version: 1.8.0
    includeCRDs: true
    namespace: system-addons
    releaseName: cert-manager
    valuesFile: cert-manager-values.yaml

  - repo: https://charts.jetstack.io
    name: cert-manager-trust
    version: 0.1.1
    releaseName: cert-manager-trust
    includeCRDs: true
    namespace: system-addons
    valuesFile: cert-manager-trust-values.yaml
      