kind: Kustomization

helmCharts:
  - repo: https://helm.linkerd.io/edge
    name: linkerd2-cni
    version: 30.0.12-edge
    releaseName: linkerd-cni
    namespace: linkerd-cni
    valuesFile: values.yaml