apiVersion: v1
kind: ConfigMap
metadata:
  name: ds-jaeger
  labels:
    grafana_datasource: "1"
    namespace: monitoring
data:
  ds-jaeger.yaml: |-
    apiVersion: 1
    datasources:
      - name: DevOps-Jaeger
        uid: devops-jaeger
        type: jaeger
        url: http://jaeger-operator-jaeger-query.monitoring:16686
        access: proxy
        isDefault: false
        editable: false
        jsonData:
          timeInterval: 30s
          nodeGraph:
            enabled: true
          search:
            hide: false
          tracesToLogs:
            datasourceUid: devops-loki
            tags: ['job', 'instance', 'pod', 'namespace']
            mappedTags: [{ key: 'service.name', value: 'service' }]
            mapTagNamesEnabled: true
            spanStartTimeShift: '1h'
            spanEndTimeShift: '1h'
            filterByTraceID: true
            filterBySpanID: true
            lokiSearch: true
