apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-ds-grafana
  labels:
    grafana_datasource: "1"
    namespace: monitoring
data:
  ds-loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: DevOps-Loki
        uid: devops-loki
        type: loki
        url: http://loki-loki-distributed-gateway.monitoring
        access: proxy
        isDefault: false
        editable: false
        jsonData:
          timeInterval: 30s
          maxLines: 1000
          derivedFields:
            # Field with internal link pointing to data source in Grafana.
            # Right now, Grafana supports only Jaeger and Zipkin data sources as link targets.
            # datasourceUid value can be anything, but it should be unique across all defined data source uids.
            - datasourceUid: devops-jaeger
              matcherRegex: "traceID=(\\w+)"
              name: TraceID
              # url will be interpreted as query for the datasource
              url: '$${__value.raw}'

            # # Field with external link.
            # - matcherRegex: "traceID=(\\w+)"
            #   name: TraceID
            #   url: 'http://jaeger-operator-jaeger-query.monitoring:16686/trace/$${__value.raw}'

            - datasourceUid: devops-tempo
              matcherRegex: "traceID=(\\w+)"
              name: TraceID
              # url will be interpreted as query for the datasource
              url: '$${__value.raw}'

            # # Field with external link.
            # - matcherRegex: "traceID=(\\w+)"
            #   name: TraceID
            #   url: 'http://tempo-tempo-distributed-query-frontend.monitoring:3100/trace/$${__value.raw}'