apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-ds-grafana
  labels:
    grafana_datasource: "1"
    namespace: monitoring
data:
  tempo-ds.yaml: |-
    apiVersion: 1
    datasources:
      - name: Tempo
        uid: tempo
        type: tempo
        url: http://tempo-tempo-distributed-query-frontend.monitoring:3100
        access: proxy
        isDefault: false
        editable: false
        jsonData:
          timeInterval: 30s
          nodeGraph:
            enabled: true
          search:
            hide: false
          serviceMap:
            datasourceUid: prometheus
          tracesToLogs:
            datasourceUid: loki
            tags: ['job', 'instance', 'pod', 'namespace']
            mappedTags: [{ key: 'service.name', value: 'service' }]
            mapTagNamesEnabled: false
            spanStartTimeShift: '1h'
            spanEndTimeShift: '1h'
            filterByTraceID: true
            filterBySpanID: true
            lokiSearch: true
