kind: Kustomization

helmCharts:
  - repo: https://jaegertracing.github.io/helm-charts
    name: jaeger-operator
    version: 2.29.0
    includeCRDs: true
    namespace: monitoring
    releaseName: jaeger-operator
    valuesFile: values.yaml