image:
  tag: 1.32.0

jaeger:
  create: true
  spec:
    allInOne:
      image: jaegertracing/all-in-one:1.32.0
    # strategy: production
    ingress:
      enabled: true
      hosts:
        - mk.jaeger.local
