apiVersion: v1
kind: Secret
metadata:
  name: reloader-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://stakater.github.io/stakater-charts
  name: reloader
  type: helm
