apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-operator-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://charts.external-secrets.io
  name: external-secrets-operator
  type: helm
