apiVersion: v1
kind: Secret
metadata:
  name: elastic-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://helm.elastic.co
  name: elastic
  type: helm
