apiVersion: v1
kind: Secret
metadata:
  name: jetstack-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://charts.jetstack.io
  name: jetstack
  type: helm
