apiVersion: v1
kind: Secret
metadata:
  name: keda-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://kedacore.github.io/charts
  name: keda
  type: helm
