apiVersion: v1
kind: Secret
metadata:
  name: istio-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://istio-release.storage.googleapis.com/charts
  name: istio
  type: helm
