apiVersion: v1
kind: Secret
metadata:
  name: dapr
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://dapr.github.io/helm-charts/
  name: dapr
  type: helm
