search:
  # -- Enable Tempo search
  enabled: true

gateway:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    # annotations:
    #   nginx.ingress.kubernetes.io/ssl-passthrough: true

    hosts:
      - host: mk.tempo.192.168.64.29.nip.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      # - secretName: tempo-gateway-tls
      - hosts:
        - mk.tempo.192.168.64.29.nip.io

traces:
  jaeger:
    # -- Enable Tempo to ingest Jaeger GRPC traces
    grpc: false
    # -- Enable Tempo to ingest Jaeger Thrift Binary traces
    thriftBinary: false
    # -- Enable Tempo to ingest Jaeger Thrift Compact traces
    thriftCompact: false
    # -- Enable Tempo to ingest Jaeger Thrift HTTP traces
    thriftHttp: false
  # -- Enable Tempo to ingest Zipkin traces
  zipkin: false
  otlp:
    # -- Enable Tempo to ingest Open Telemetry HTTP traces
    http: true
    # -- Enable Tempo to ingest Open Telemetry GRPC traces
    grpc: true
  # -- Enable Tempo to ingest Open Census traces
  opencensus: false
  # -- Enable Tempo to ingest traces from Kafka. Reference: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kafkareceiver
  kafka: {}


# ingester:
#   persistence: true
#   size: 2Gi
#   storageClass: 
  
# ServiceMonitor configuration
serviceMonitor:
  # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
  enabled: true


# Rules for the Prometheus Operator
prometheusRule:
  # -- If enabled, a PrometheusRule resource for Prometheus Operator is created
  enabled: true
  # -- Alternative namespace for the PrometheusRule resource
  namespace: null
  # -- PrometheusRule annotations
  annotations: {}
  # -- Additional PrometheusRule labels
  labels: {}
  # -- Contents of Prometheus rules file
  groups: # []
  - name: tempo-rules
    rules:
      - record: job:tempo_request_duration_seconds_bucket:sum_rate
        expr: sum(rate(tempo_request_duration_seconds_bucket[1m])) by (le, job)
      - record: job_route:tempo_request_duration_seconds_bucket:sum_rate
        expr: sum(rate(tempo_request_duration_seconds_bucket[1m])) by (le, job, route)
      - record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
        expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (node, namespace, pod, container)