global:
  # image:
  #   # -- Overrides the Docker registry globally for all images
  #   registry: null
  # # -- Overrides the priorityClassName for all pods
  # priorityClassName: null
  # # -- configures cluster domain ("cluster.local" by default)
  # clusterDomain: "cluster.local"
  # # -- configures DNS service name
  dnsService: "coredns"
  # -- configures DNS service namespace
  # dnsNamespace: "kube-system"

gateway:
  ingress:
    enabled: true
    # Newly added optional property
    ingressClassName: nginx
    hosts:
      - host: mk.tempo.local
        paths:
          # New data structure introduced
          - path: /
            # Newly added optional property
            pathType: Prefix

ingester:
  persistence: true
  size: 2Gi
  
# ServiceMonitor configuration
serviceMonitor:
  # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
  enabled: true


# Rules for the Prometheus Operator
prometheusRule:
  # -- If enabled, a PrometheusRule resource for Prometheus Operator is created
  enabled: true
  # -- Alternative namespace for the PrometheusRule resource
  namespace: null
  # -- PrometheusRule annotations
  annotations: {}
  # -- Additional PrometheusRule labels
  labels: {}
  # -- Contents of Prometheus rules file
  groups: # []
  - name: tempo-rules
    rules:
      - record: job:tempo_request_duration_seconds_bucket:sum_rate
        expr: sum(rate(tempo_request_duration_seconds_bucket[1m])) by (le, job)
      - record: job_route:tempo_request_duration_seconds_bucket:sum_rate
        expr: sum(rate(tempo_request_duration_seconds_bucket[1m])) by (le, job, route)
      - record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
        expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (node, namespace, pod, container)