kind: Kustomization

resources:
  - "./resources/linkerd-viz-ingress.yaml"

helmCharts:
  - repo: https://helm.linkerd.io/edge
    name: linkerd-viz
    version: 30.1.0-edge
    releaseName: linkerd-viz
    namespace: linkerd-viz
    valuesFile: values.yaml