kind: Kustomization

resources:
  - "./resources/linkerd-viz-ingress.yaml"

helmCharts:
  - repo: https://helm.linkerd.io/stable
    name: linkerd-viz
    version: 2.11.1
    releaseName: linkerd-viz
    namespace: linkerd-viz
    valuesFile: values.yaml