apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = false
    reporting_enabled = false

    [grafana_net]
    url = https://grafana.com

    [log]
    mode = console

    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [feature_toggles]
    enable = tempoSearch tempoBackendSearch tempoServiceGraph

    [security]
    cookie_secure = true
    cookie_samesite = strict
    strict_transport_security = true
    strict_transport_security_subdomains = true

    [auth]
    disable_login_form = true

    [server]
    root_url = mk.grafana.local
    
    [log]
    mode = console
    level = warning
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
