apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-promotheus-exporter
  labels:
    name: otel-promotheus-exporter
spec:
  selector:
    matchNames:
      - otel-collector-daemonset-collector-monitoring
  podMetricsEndpoints:
    - port: monitoring
