apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: otel-collector-prometheus-exporter
  labels:
    name: otel-collector-prometheus-exporter
    release: prometheus-operator
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector-daemonset-collector
  podMetricsEndpoints:
    - targetPort: 8080
      honorLabels: false