apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: otel-promotheus-exporter
  labels:
    name: otel-promotheus-exporter
    release: prometheus-operator
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector-daemonset-collector
  podMetricsEndpoints:
    - targetPort: 8888