apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-prometheus-exporter
  labels:
    name: otel-collector-prometheus-exporter
    release: prometheus-operator
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector-daemonset-collector
  endpoints:
    - port: prometheus-exporter-listener
