apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  labels:
    name: otel-collector
    release: prometheus-operator
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector-daemonset-collector-monitoring
  endpoints:
    - port: monitoring
