kind: Kustomization

helmCharts:
  - repo: https://charts.external-secrets.io
    name: external-secrets
    version: 0.5.5
    releaseName: external-secrets
    namespace: system-addons
    valuesFile: values.yaml
    includeCRDs: true