kind: Kustomization
namespace: ingress-nginx
metadata:
  labels:
    argocd-project: tools

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.0.16
    releaseName: nginx-ingress
    valuesFile: values.yaml