kind: Kustomization

resources:
  - "./resources/cluster-secret-store.yaml"

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.4.3
    releaseName: external-secrets
    valuesFile: values.yaml
    includeCRDs: true